### ISSUE TITLE
Calculator of area covered by gaze (in px and degrees)

### ISSUE THREAD

**Issue by PMarmalyuk** [PMarmalyuk/EyeTrackingProject#17]

**Comment by PMarmalyuk** [comment]
Have been done during work for Ushakov D.V.
Need to make it a SubFunction!

**Comment by deslion** [comment]
Added pointsArea realization: [https://github.com/deslion/EyeTrackingProject/commit/9c75a56d8be80d79cc266379d73ed04a693c3798](url)
