### ISSUE TITLE
Calculator of first fixation parameters

### ISSUE THREAD

**Issue by PMarmalyuk** [PMarmalyuk/EyeTrackingProject#18]

**Comment by deslion** [comment]
Is it necessary to calculate only for the first fixation? Maybe we should make list of fixations, saccades, glissades etc, all with their durations and center coordinates? I have some ideas about code, but can't figure out, what I should have as input and output.

**Comment by PMarmalyuk** [comment]
This is an issue for estimator. I'll try to implement it during next two weeks.

**Comment by PMarmalyuk** [comment]
This is an issue of selecting values of event parameters that have been already calculated by eventAnalyzer, not recalculating them separately. This can be done by param estimator of specific type.
