### ISSUE TITLE
Calculator of number of saccades with orientation within specified interval

### ISSUE THREAD

**Issue by PMarmalyuk** [PMarmalyuk/EyeTrackingProject#19]

**Comment by deslion** [comment]
As a start point, maybe we should make such date frames: "marker"-"x"-"y"-"dur"-"tstart"-"orient"?
And how exactly will the orientation be alike? Factor? "forward"-"backward"?
Oh, maybe make "h.orient"-"v.orient"? "for-"-"back-" and "up-"-"down-"-ward?

**Comment by PMarmalyuk** [comment]
Just try to solve another issues (detectors + visualisations), because such calculation can be implemented as abstract counter with filtration by events factors.
