### ISSUE TITLE
Test IVT (simple version), ANH and IDT event detection algorithms

### ISSUE THREAD

**Issue by PMarmalyuk** [PMarmalyuk/EyeTrackingProject#3]
It is needed to test and debug all event detection algorithms after solving their isolation issue.

**Comment by deslion** [comment]
So, I've been testing these algorithms for some time. Some ideas:
1. ANH works quite nice, and such a great count of gaps depends on settings - minFix- and minSac-durations. And also on max vels.
2. There is a problem with "How to filter data". ANH detection quality depends very much on it.
3. IVT without post-processing works, and also isolated.
