### ISSUE TITLE
Append AOI markers to trajectory data

### ISSUE THREAD

**Issue by PMarmalyuk** [PMarmalyuk/EyeTrackingProject#35]

**Comment by nezdeshni** [comment]
Already done, function return data.frame with x,y point coordinats column and column with AOI name for each point.

**Comment by PMarmalyuk** [comment]
Is there a method which use this function to find AOI markers and then update the DataRecord object? 
As I understand, you have implemented a function which takes x, y and AOI information and returns x,y + AOI name. 
Thus we need a core method which uses this function. For example, see how coreFilter works (with filtering function isolated from class structure).

**Comment by nezdeshni** [comment]
Ok, get it)
