### ISSUE TITLE
Debug IVT event detection function (with post processing)

### ISSUE THREAD

**Issue by PMarmalyuk** [PMarmalyuk/EyeTrackingProject#4]
It is needed to figure out why the resulting event markers vector length is not equal to samples number in a trajectory.

It would be great if vectorized version of the algorithm is implemented. Try :)

**Comment by deslion** [comment]
IVT doesn't eat samples now.
[https://github.com/deslion/EyeTrackingProject/commit/c0c1cf280dc0c78cbda76b743d84796775b78c38](url)

**Comment by deslion** [comment]
Finally did it. [https://github.com/deslion/EyeTrackingProject/commit/246771b25c8bc3d0e981219142545b586c85adf1](url)
It seems so.

**Comment by PMarmalyuk** [comment]
Grats)
